.\" Manpage for guh-cli.
.\" Contact simon.stuerz@guh.guru to correct errors or typos.
.TH man 1 "May 2015" "1.0" "guh-cli man page"
.SH NAME
guh-cli \- guh command line interface written in python 
.SH SYNOPSIS
.B guh-cli
[\fIHOST\fR] [\fIPORT\fR]
.SH DESCRIPTION
The guh-cli (command line interface) is an admin tool written in python to communicate 
with the guh JSON-RPC API and test functionality of guh.
.SH DEFAULTS
By default guh-cli will use 
.IR localhost 
(127.0.0.1) for
.BR [HOST]
and
.IR 1234 
for
.BR [PORT] . 
Both arguments are optional.
.SH EXAMPLES
.TP
guh-cli 192.168.1.5 1234
.SH SEE ALSO
Full documentation at: <https://github.com/guh/guh/wiki/guh-cli>
.SH "REPORTING BUGS"
Git repository on github: <https://github.com/guh/guh-cli/issues>
.SH AUTHOR
Written by Simon Stürz
.SH COPYRIGHT
Copyright \(co 2015 Simon Stürz <simon.stuerz@guh.guru>.
.br
License GPLv2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
