#!/usr/bin/env python

# -*- coding: UTF-8 -*-

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#                                                                         #
#  Copyright (C) 2015 Simon Stuerz <simon.stuerz@guh.guru>                #
#                                                                         #
#  This file is part of guh-cli.                                          #
#                                                                         #
#  guh-cli is free software: you can redistribute it and/or modify        #
#  it under the terms of the GNU General Public License as published by   #
#  the Free Software Foundation, version 2 of the License.                #
#                                                                         #
#  guh-cli is distributed in the hope that it will be useful,             #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
#  GNU General Public License for more details.                           #
#                                                                         #
#  You should have received a copy of the GNU General Public License      #
#  along with guh. If not, see <http://www.gnu.org/licenses/>.            #
#                                                                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

import sys
import os
import traceback
import curses
import argparse

from guh import __version__
from guh import guh
from guh import mainmenu


###########################################################
# Main 
###########################################################

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='The guh-cli (command line interface) is an admin tool written in python to communicate with the guh daemon JSON-RPC API and test functionality of guh.')
    parser.add_argument('-v','--version', action='version', version=__version__)
    parser.add_argument('--host', type=str, default='localhost', help='the location of the guh daemon (default 127.0.0.1)')
    parser.add_argument('--port', type=int, default=2222, help='the port of the the guh daemon (default 2222)')
    parser.add_argument('--push-button', action="store_true", dest="pushbutton", default=False, help='Use pushbutton authentication method instead of username password')

    args = parser.parse_args()

    # check connection
    if not guh.init_connection(args.host, args.port, args.pushbutton):
        exit()

    os.system('clear')
    screen = curses.initscr()
    try:
        # run main menu
        mainmenu.start(args.host, args.port)
    finally:
        curses.endwin()
        os.system('clear')
        print "Bye, have a nice day! :)"    



